# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

#link_with 'OAWork'

platform :ios, '9.0'

target ‘OAWork’ do

pod 'SVProgressHUD'
pod 'Reachability'
pod 'RCPopoverView'
pod 'AFNetworking' 
pod 'iConsole'
pod 'Masonry' 
pod 'SDWebImage' 
pod 'MJRefresh'
pod 'VIPhotoView', '~> 0.1'
pod 'MWPhotoBrowser'
pod 'Bugtags'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'RadioButton'
pod 'RGB'
pod 'RAlertView'
pod 'JCAlertController'
end
